### ISSUE TITLE
[BUG] Aborted Stage 3 process saves incomplete mkv file

### ISSUE THREAD

**Issue by sharkysi** [ack00gar/FunGen-AI-Powered-Funscript-Generator#39]
If you start a stage 3, with the save/re-use video option set, and then abort the process while still on stage 1, a incomplete mkv file is left and then if you click to start the process again it tries to use the incomplete mkv.

2025-07-14 09:49:11 - application.logic.app_logic - WARNING  - [video_processor.get_frames_batch:432] - get_frames_batch: Incomplete data for frame 0 (read 0/1228800). P2 Stderr: [h264 @ 000001de1ab6e3c0] Hardware is lacking required capabilities
[h264 @ 000001de1ab6e3c0] Failed setup for format cuda: hwaccel initialisation returned error.
Impossible to convert between the formats supported by the filter 'graph -1 input from stream 0:0' and the filter 'auto_scale_0'
[vf#0:0 @ 000001de1aec1680] Error reinitializing filters!
[vf#0:0 @ 000001de1aec1680] Task finished with error code: -40 (Function not implemented)
[vf#0:0 @ 000001de1aec1680] Terminating thread with return code -40 (Function not implemented)
[vost#0:0/rawvideo @ 000001de1af45840] [enc:rawvideo @ 000001de1ac2b540] Could not open encoder before EOF
[vost#0:0/rawvideo @ 000001de1af45840] Task finished with error code: -22 (Invalid argument)
[vost#0:0/rawvideo @ 000001de1af45840] Terminating thread with return code -22 (Invalid argument)
[out#0/rawvideo @ 000001de1b0a8040] Nothing was written into output file, because at least one of its streams received no packets.

**Comment by ack00gar** [comment]
Should be fixed, opening a video will have the process check for preprocessed file and switch to it only if it has the same number of frames than the original file.

**Comment by sharkysi** [comment]
still not working - warning received and it processes the existing mkv file

`2025-07-21 11:29:49 - application.logic.app_logic - WARNING  - [video_processor.get_frames_batch:455] - get_frames_batch: Incomplete data for frame 0 (read 0/1228800). P2 Stderr: [h264 @ 00000151063585c0] Hardware is lacking required capabilities
[h264 @ 00000151063585c0] Failed setup for format cuda: hwaccel initialisation returned error.
Impossible to convert between the formats supported by the filter 'graph -1 input from stream 0:0' and the filter 'auto_scale_0'
[vf#0:0 @ 0000015106891200] Error reinitializing filters!
[vf#0:0 @ 0000015106891200] Task finished with error code: -40 (Function not implemented)
[vf#0:0 @ 0000015106891200] Terminating thread with return code -40 (Function not implemented)
[vost#0:0/rawvideo @ 00000151063bed00] [enc:rawvideo @ 000001510632ae00] Could not open encoder before EOF
[vost#0:0/rawvideo @ 00000151063bed00] Task finished with error code: -22 (Invalid argument)
[vost#0:0/rawvideo @ 00000151063bed00] Terminating thread with return code -22 (Invalid argument)
[out#0/rawvideo @ 00000151064077c0] Nothing was written into output file, because at least one of its streams received no packets.
2025-07-21 11:29:49 - application.logic.app_logic - INFO     - [video_processor._terminate_process:832] - Batch Pipe 2/Main process terminated.
2025-07-21 11:29:49 - application.logic.app_logic - WARNING  - [video_processor._get_specific_frame:531] - Failed to retrieve specific frame 0 after batch fetch. FFmpeg might have failed or frame out of bounds.`
